name: onnxscript
channels:
  - defaults
  - nvidia/label/cuda-11.8.0
  - conda-forge
dependencies:
  - python=3.10
  - cuda-version==11.8 
  - cudnn==8.9.7.29
  - pip:
    - -r requirements-dev.txt

variables:
  OPENCV_IO_ENABLE_OPENEXR: "1"
  CUDA_PATH: ""